### ISSUE TITLE
Difficult to read subtitles in Chrome

### ISSUE THREAD

**Issue by tatzyr** [tatzyr/subsubdeecee-extension#3]
Compared to Firefox, Chrome's subtitles are harder to read. One reason is that the translation is done in long sentence units to improve translation quality.

**Firefox**:

![screenshot_firefox](https://github.com/tatzyr/subsubdeecee-extension/assets/1025461/91c0c25e-70ff-4fcc-b51d-1dabd02bf5a4)

**Chrome**:

![screenshot_chrome](https://github.com/tatzyr/subsubdeecee-extension/assets/1025461/47ca3e77-3430-4ac1-920f-cd1e4bac3c34)

Subtitles can be styled with the CSS pseudo-element `::cue`. However, there are the following problems

* The `background` is not applied in Chrome.
  ```css
  video::cue {
    font-size: 1em; /* OK */
    background: #000000;  /* does not work! */
  }
  ```

* The style is also applied to Apple's official English subtitles. This may break Apple's official English subtitle display.
